### ISSUE TITLE
Gatsby environment variables for config

### ISSUE THREAD

**Issue by mickeyreiss-visor** [stephenmathieson/gatsby-plugin-segment#2]
I'm trying to use a GATSBY_ environment variable to configure my SEGMENT_KEY but it seems that gatsby-config.js gets evaluated without process.env.GATSBY_ENV substitution. Would it be possible to default to reading the segment key from .env.* files if they are present? Is there already a recommended way to switch config based on environment?

**Comment by stephenmathieson** [comment]
I'm not sure what significance `GATSBY_`-prefixed env vars have (I'm not following the project too closely these days), but you should be able to do something like:

```
module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-segment',
      options: {
        writeKey: process.env.SEGMENT_KEY
      }
    }
  ]
}
```

Then just build like this:

```
$ SEGMENT_KEY=your_stage_key gatsby build
$ SEGMENT_KEY=your_prod_key gatsby build
```

Does this solve your problem?

**Comment by mickeyreiss-visor** [comment]
Yes, this solves my problem. Gatsby has a mechanism to store environment variables per environment in files named e.g. `.env.production`, and I was hoping to be able to use that. Thanks for your quick support!

**Comment by stephenmathieson** [comment]
Ah cool, I didn't know that. There may be a way to tap into that from the config file, but I'm not aware of one.

Let me know if you figure it out, as it'd be nice to list in the README here =]
