### ISSUE TITLE
@segment/snippe Error

### ISSUE THREAD

**Issue by gnunua** [stephenmathieson/gatsby-plugin-segment#3]
When installing the plugin (`npm i gatsby-plugin-segment` ) the following error message appears: 

npm ERR! code E404
npm ERR! 404 Not Found: @segment/snippet@^4.0.1

**Comment by stephenmathieson** [comment]
I'm unable to reproduce this, and without more information, can't help much.

Feel free to reopen with a full list of reproduction steps.
