### ISSUE TITLE
Please add more infos about how to use

### ISSUE THREAD

**Issue by thebarty** [stephenmathieson/gatsby-plugin-segment#4]
Hi there,

first of all: THANKS a lot for making this easy!

A few questions pop in my mind, which might also popup for other users:

1) Is there anything tracked automatically? P.e. page-views?
2) How do I access `analytics` if I want to track custom stuff?

Maybe add the answers to the readme?

**Comment by benjaminhoffman** [comment]
@thebarty 
try using: https://github.com/benjaminhoffman/gatsby-plugin-segment-js

it's up to date and much more robust!  feel free to open an issue if you have any questions or comments.

**Comment by stephenmathieson** [comment]
Hello!

1. Yes, page views are tracked automagically.
2. Call `window.analytics.track()` 😉 

PR welcome for updating the README.
