### ISSUE TITLE
deprecation warning?

### ISSUE THREAD

**Issue by benjaminhoffman** [stephenmathieson/gatsby-plugin-segment#5]
@stephenmathieson yo dude... hope all is well in Mich!

looking for a maintainer of this?  or maybe we can deprecate this in favor of https://github.com/benjaminhoffman/gatsby-plugin-segment-js ? 🙏 

yours truly.

**Comment by stephenmathieson** [comment]
This repo receives very little traffic/attention, gets only a few 100 installs per month, and is arguably feature complete. There's not much to do as a maintainer.

This said, sure. I've been using [react-static](https://github.com/nozzle/react-static) (it's much nicer than Gatsby) and/or Next.js for things lately, so I have little-to-no time for this package.

I've added you as a collaborator here. Feel free to do what you please, but you must respect SEMVER. If you send me your npm account/email, I can add you there too.

**Comment by benjaminhoffman** [comment]
email sent.  thank you. will follow SEMVER.

react-static. nice find. i may have a project i could use this for.  in their post, the claims about Gatsby are somewhat valid.  im mostly curious in 5 years, which of the current ssr solutions will still be around.

**Comment by stephenmathieson** [comment]
Cool, I'll add you Monday. Thanks!

IMO nothing current in the front-end world will be valid 5 years from now. Think jQuery. Think fatigue. I'm almost over it already haha. Two of the few marketing sites I've built in the past few months have been vanilla HTML, CSS and JS. Nothing close to fancy, and super easy to "hand off" to any team.
